### ISSUE TITLE
Release an APK

### ISSUE THREAD

**Issue by amitness** [jianhuachentw/MiTomato#1]
Please push a compiled apk to the repo. I just got a MI band and want to try this app out.

**Comment by jianhuachentw** [comment]
Uploaded a compiled apk to "apks" folder. Enjoy. :)

**Comment by amitness** [comment]
Thanks for the APK.

When I click "Search", no bluetooth devices are shown. Is there any setting to toggle?

**Comment by amitness** [comment]
Thanks a lot.
